import "./../globals.css";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import Sidebar from "@/components/sidebar";
import ModalProvider from "@/components/providres/modal-provider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

const dm_sans = DM_Sans({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link href="https://cdn.syncfusion.com/ej2/material.css" rel="stylesheet" />
      </head>
      <body className={cn(dm_sans.className, "h-screen")}>
        <ModalProvider />
        <Toaster />
        <div className="grid gap-x-5 bg-white grid-cols-1 md:grid-cols-[250px_1fr] h-screen">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
