import "./../globals.css";
import type { Metadata } from "next";
import { Inter, Roboto_Mono, DM_Sans } from "next/font/google";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

const notoSans = Roboto_Mono({
  weight: ["400", "200", "300", "700"],
  subsets: ["latin"],
  display: "swap",
});

const dm_sans = DM_Sans({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <div className="grid grid-cols-dashboard-layout h-screen">
          <Sidebar />
          <div className="bg-[#F3F9F8]">{children}</div>
        </div>
      </body>
    </html>
  );
}
